In [23]:
import numpy as np
import pandas as pd

In [24]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [25]:
df=pd.read_csv('covid_toy.csv')

In [26]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [27]:
df['city'].value_counts()

Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64

In [28]:
df['cough'].value_counts()

Mild      62
Strong    38
Name: cough, dtype: int64

In [29]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2,random_state=0)

In [31]:
X_train

age  gender  fever   cough       city
43   22  Female   99.0    Mild  Bangalore
62   56  Female  104.0  Strong  Bangalore
3    31  Female   98.0    Mild    Kolkata
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
96   51  Female  101.0  Strong    Kolkata
67   65    Male   99.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
47   18  Female  104.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

**Filling the Missing Values in the Column**

In [34]:
from sklearn.impute import SimpleImputer
s=SimpleImputer()
#X_train_fever=fit_transform(X_train[['fever']])
#X_test_fever=fit_transform(X_test[['fever']])



In [36]:
X_train_fever=s.fit_transform(X_train[['fever']])
X_test_fever=s.fit_transform(X_test[['fever']])
X_train_fever

array([[ 99.        ],
       [104.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [102.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [102.        ],
       [ 98.        ],
       [100.91549296],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.91549296],
       [100.91549296],
       [104.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [ 98.        ],
       [100.        ],
       [100.91549296],
       [103.        ],
       [104.        ],
       [ 99

In [37]:
X_train.shape

(80, 5)

In [38]:
X_train_fever.shape

(80, 1)

**Ordinal Encoding**

In [44]:
# ordinal encoding cough column
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])

In [40]:
X_train_cough.shape

(80, 1)

In [43]:
X_test_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.]])

**One Hot Encoding**

In [48]:
ohe=OneHotEncoder(drop='first',sparse=False)
X_train_gc=ohe.fit_transform(X_train[['gender','city']])
X_test_gc=ohe.fit_transform(X_test[['gender','city']])



/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [49]:
X_train_gc.shape

(80, 4)

In [52]:
X_train_age=X_train.drop(columns=['gender','city','fever','cough']).values
X_test_age=X_test.drop(columns=['gender','city','fever','cough']).values

In [53]:
X_train_transformed=np.concatenate((X_train_age,X_train_gc,X_train_fever,X_train_cough),axis=1)

In [54]:
X_train_transformed

array([[ 22.        ,   0.        ,   0.        ,   0.        ,
          0.        ,  99.        ,   0.        ],
       [ 56.        ,   0.        ,   0.        ,   0.        ,
          0.        , 104.        ,   1.        ],
       [ 31.        ,   0.        ,   0.        ,   1.        ,
          0.        ,  98.        ,   0.        ],
       [ 75.        ,   0.        ,   1.        ,   0.        ,
          0.        , 104.        ,   1.        ],
       [ 72.        ,   1.        ,   0.        ,   0.        ,
          0.        ,  99.        ,   0.        ],
       [ 66.        ,   1.        ,   0.        ,   0.        ,
          0.        ,  99.        ,   1.        ],
       [ 14.        ,   1.        ,   0.        ,   0.        ,
          0.        , 101.        ,   1.        ],
       [ 10.        ,   0.        ,   0.        ,   1.        ,
          0.        ,  98.        ,   1.        ],
       [ 24.        ,   1.        ,   0.        ,   1.        ,
          0.    

In [55]:
X_train_transformed.shape

(80, 7)

**Computing and Easy Technique of Encoding**

In [56]:
from sklearn.compose import ColumnTransformer

In [62]:
transformer=ColumnTransformer(transformers=[
    ('tf1',SimpleImputer(),['fever']),
    ('tf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
])

In [63]:
transformer.fit_transform(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0. 

In [65]:
transformer.fit_transform(X_train).shape

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 6)